### ISSUE TITLE
Zenodo Hardcover ISBN can't be gathered from \ISBNhardcover

### ISSUE THREAD

**Issue by kopeckyf** [langsci/pypi#19]
`zenodo.py` seems to depend on this format:

```latex
\renewcommand{\lsISBNhardcover}{978-3-.....}
```

This could become an issue since we use the command `\ISBNhardcover[]{}` since commit https://github.com/langsci/langscibook/commit/48e29e5dcc8a3adee29775abf35e6d82ae660509 in order to accommodate EAN+2 ISBN addons.

`zenodo.py` does not recognise ISBNs from `\ISBNhardcover[]{}` and results in an error.

**Comment by Glottotopia** [comment]
For Zenodo, the main functionality is to point to the digital ISBN, since this is, well, digital. 
The hardcover ISBN is also related, true, but I cannot see any practical use for that. 
The fact that we fail to retrieve and hence fail to link the hardcover ISBN will probably have zero consequences.

**Comment by kopeckyf** [comment]
My bug report was not very clear. 

`langscibook.cls` defines `\ISBNdigital`, `\ISBNhardcover`, etc.:

https://github.com/langsci/langscibook/blob/bcd22af301323f44c47a57deac2a3ae40f3e5f5e/langscibook.cls#L82

When these are used in a `localmetadata.tex` to configure the ISBNs of the book, `registerzenodo.py` does not work, because it seems to be looking for `\renewcommand{\lsISBNhardcover}`, which is a different way of inputting the ISBN. The error message is this:

```python
Traceback (most recent call last):
  File "/home/felix/Github/280/registerzenodo.py", line 30, in <module>
    book = zenodo.Book(extracommunities=extracommunities)
  File "/home/felix/Github/pypi/langsci/langsci/zenodo.py", line 73, in __init__
    self.getBookMetadata()
  File "/home/felix/Github/pypi/langsci/langsci/zenodo.py", line 112, in getBookMetadata
    self.digitalisbn = ISBNP.search(localmetadata).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

The issue is that sometimes you want to input the ISBN via the user-level command `\ISBNhardcover` instead of going through `\renewcommand{\lsISBNhardcover}`. One example where this happens is when you want to functionalities of `\ISBNhardcover` such as giving the EAN+2 as optional arguments. 

So it would be good if `registerzenodo.py` could scan for either the user-level command or the `\renewcommand` way of providing ISBNs.
