### ISSUE TITLE
txt2bib.py returned "bad escape"

### ISSUE THREAD

**Issue by kopeckyf** [langsci/pypi#2]
```
python3 txt2bib.py bib.txt 
Traceback (most recent call last):
  File "txt2bib.py", line 3, in <module>
    from langscibibtex import Record
ModuleNotFoundError: No module named 'langscibibtex'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "txt2bib.py", line 5, in <module>
    from langsci.langscibibtex import Record 
  File "/home/felix/virtenv/langsci/lib/python3.6/site-packages/langsci/langscibibtex.py", line 9, in <module>
    import normalizebib
  File "/home/felix/Github/pypi/langsci/wrapperscripts/normalizebib.py", line 39, in <module>
    CITE = re.compile(r'\cite[yeargenltp]*(?:\[.*?\])?\{(.*?)\}')
  File "/usr/lib/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.6/sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/usr/lib/python3.6/sre_parse.py", line 502, in _parse
    code = _escape(source, this, state)
  File "/usr/lib/python3.6/sre_parse.py", line 401, in _escape
    raise source.error("bad escape %s" % escape, len(escape))
sre_constants.error: bad escape \c at position 0
```

**Comment by kopeckyf** [comment]
This error occured in Python 3.6.6. on Ubuntu 18.04.1 LTS
